"""Module for games."""
from noregret.games.black_box import (
    BlackBoxGame,
    open_spiel_game,
    SequenceFormStrategyProfile,
    Simulation,
    StrategyProfile,
    TupleStrategyProfile,
    UniformStrategyProfile,
)
from noregret.games.extensive_form import (
    ExtensiveFormGame,
    to_extensive_form_game,
    TwoPlayerExtensiveFormGame,
    TwoPlayerZeroSumExtensiveFormGame,
)
from noregret.games.games import Game, TwoPlayerGame, TwoPlayerZeroSumGame
from noregret.games.multilinear import (
    MultilinearGame,
    TwoPlayerMultilinearGame,
    TwoPlayerZeroSumMultilinearGame,
)
from noregret.games.normal_form import (
    AssuranceGame,
    BattleOfTheSexes,
    Chicken,
    GiftExchangeGame,
    MatchingPennies,
    matrix_game,
    NormalFormGame,
    PrisonersDilemma,
    PureCoordination,
    RockPaperScissors,
    RockPaperScissorsPlus,
    RockPaperSuperscissors,
    StagHunt,
    TwoPlayerNormalFormGame,
    TwoPlayerZeroSumNormalFormGame,
)

__all__ = (
    'AssuranceGame',
    'BattleOfTheSexes',
    'BlackBoxGame',
    'Chicken',
    'ExtensiveFormGame',
    'Game',
    'GiftExchangeGame',
    'MatchingPennies',
    'matrix_game',
    'MultilinearGame',
    'NormalFormGame',
    'open_spiel_game',
    'PrisonersDilemma',
    'PureCoordination',
    'RockPaperScissors',
    'RockPaperScissorsPlus',
    'RockPaperSuperscissors',
    'SequenceFormStrategyProfile',
    'Simulation',
    'StagHunt',
    'StrategyProfile',
    'to_extensive_form_game',
    'TupleStrategyProfile',
    'TwoPlayerExtensiveFormGame',
    'TwoPlayerGame',
    'TwoPlayerMultilinearGame',
    'TwoPlayerNormalFormGame',
    'TwoPlayerZeroSumExtensiveFormGame',
    'TwoPlayerZeroSumGame',
    'TwoPlayerZeroSumMultilinearGame',
    'TwoPlayerZeroSumNormalFormGame',
    'UniformStrategyProfile',
)
